/* Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */

package lc.q0389.FindtheDifference;

public class Solution {
    public char findTheDifference(String s, String t) {
    	int[] ctb= new int[26];
    	for(int i=0;i<s.length();i++)
    		ctb[s.charAt(i)-'a']++;
    	for(int i=0;i<t.length();i++)
    	{
    		ctb[t.charAt(i)-'a']--;
    		if(ctb[t.charAt(i)-'a']<0)
    			return t.charAt(i);
    	}
    	return 0;
    }
}
